export const THEME_VARS: Record<string, Record<string, string>> = {
  WARM: {
    '--lp-bg': '#fdf8f3',
    '--lp-surface': '#ffffff',
    '--lp-text': '#3d2c1e',
    '--lp-text-secondary': '#7a6555',
    '--lp-border': '#e8ddd3',
    '--lp-font-heading': "'Plus Jakarta Sans', sans-serif",
    '--lp-font-body': "'Plus Jakarta Sans', sans-serif",
    '--lp-radius': '16px',
  },
  MODERN: {
    '--lp-bg': '#f8fafc',
    '--lp-surface': '#ffffff',
    '--lp-text': '#0f172a',
    '--lp-text-secondary': '#64748b',
    '--lp-border': '#e2e8f0',
    '--lp-font-heading': "'Plus Jakarta Sans', sans-serif",
    '--lp-font-body': "'Plus Jakarta Sans', sans-serif",
    '--lp-radius': '12px',
  },
  MINIMAL: {
    '--lp-bg': '#ffffff',
    '--lp-surface': '#fafafa',
    '--lp-text': '#18181b',
    '--lp-text-secondary': '#71717a',
    '--lp-border': '#f4f4f5',
    '--lp-font-heading': "'Plus Jakarta Sans', sans-serif",
    '--lp-font-body': "'Plus Jakarta Sans', sans-serif",
    '--lp-radius': '8px',
  },
  BOLD: {
    '--lp-bg': '#0a0a0a',
    '--lp-surface': '#171717',
    '--lp-text': '#fafafa',
    '--lp-text-secondary': '#a1a1aa',
    '--lp-border': '#27272a',
    '--lp-font-heading': "'Plus Jakarta Sans', sans-serif",
    '--lp-font-body': "'Plus Jakarta Sans', sans-serif",
    '--lp-radius': '12px',
  },
};
